site_name: Cosmos Keyboard Generator
site_dir: target/mkdocs
site_url: https://ryanis.cool/cosmos/
site_description: Design a keyboard that fits your hand perfectly.
repo_name: rianadon/Cosmos-Keyboards
repo_url: https://github.com/rianadon/Cosmos-Keyboards
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/cosmos-icon.png
  favicon: assets/cosmos-icon.png
  palette:
    primary: custom
    accent: teal
  icon:
    repo: fontawesome/brands/github
    admonition:
      tip: material/fountain-pen-tip
  features:
    - navigation.top
    - navigation.tabs
    - content.code.copy

plugins:
  - search
  - awesome-pages
  - privacy:
      cache_dir: target/privacy
  - blog:
      post_url_format: "{slug}"
      archive: false
      categories: true
      authors: false
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date

hooks:
  - src/mkdocs/video.py
  - src/mkdocs/image.py
  - src/mkdocs/social.py

extra:
  analytics:
    provider: custom


extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.9/katex.min.css

markdown_extensions:
  - attr_list
  - admonition
  - md_in_html
  - smarty
  - sane_lists
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true
